<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var $block \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable*/
$_product    = $block->getProduct();
$_attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <?php foreach ($_attributes as $_attribute): ?>
        <div class="field configurable required">
            <label class="label" for="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>">
                <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>

                <?php
                // BEGIN EDIT
                $optionName = $_attribute->getProductAttribute()->getStoreLabel();
                /** @var \Kraken\ProductOptionsTooltips\Helper\Data $helper */
                $helper = $this->helper(\Kraken\ProductOptionsTooltips\Helper\Data::class);
                $optionTooltip = $helper->getOptionTooltip($optionName, $block->getProduct()->getSku());
                $optionTooltipId = $_attribute->getProductAttribute()->getAttributeId() . '_option_tooltip';

                if ($optionTooltip):

                    ?>

                    <span class="tooltip-info" aria-describedby="#<?= $optionTooltipId; ?>" data-tooltip-content="#<?= $optionTooltipId; ?>">More info</span>

                    <div class="hidden tooltip-content">
                        <div id="<?= $optionTooltipId; ?>">
                            <?= $optionTooltip; ?>
                        </div>
                    </div>

                    <script type="text/x-magento-init">
                    {
                        "*": {
                            "activateTooltipster": {}
                        }
                    }
                    </script>

                <?php endif; ?>
                <?php // END EDIT ?>

            </label>
            <div class="control">
                <select name="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>]"
                        data-selector="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>]"
                        data-validate="{required:true}"
                        id="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>"
                        class="super-attribute-select">
                    <option value=""><?= /* @escapeNotVerified */ __('Choose an Option...') ?></option>
                </select>
            </div>
        </div>
    <?php endforeach; ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "configurable": {
                    "spConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                    "gallerySwitchStrategy": "<?php /* @escapeNotVerified */ echo $block->getVar('gallery_switch_strategy',
                        'Magento_ConfigurableProduct') ?: 'replace'; ?>"
                }
            },
            "*" : {
                "Magento_ConfigurableProduct/js/catalog-add-to-cart": {}
            }
        }
    </script>
<?php endif;?>
